version: '3.8'

services:
  postgres:
    image: postgres:17.4@sha256:7f29c02ba9eeff4de9a9f414d803faa0e6fe5e8d15ebe217e3e418c82e652b35
    entrypoint: /entrypoint.sh
    ports:
      - "5432:5432"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./create_databases.sh:/startup-initdb.d/create_databases.sh
      - ./create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    tty: true
    stdin_open: true
